name: dns-manager

services:
    backend:
        container_name: dns-manager-backend
        build:
            context: ./backend
            dockerfile: ./docker/Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "${API_PORT-9000}:8000"
        networks:
            - dnsnet
    frontend:
        container_name: dns-manager-frontend
        build:
            context: ./webapp
            dockerfile: ./docker/Dockerfile
            args:
                VITE_HTTPS_ENABLED: ${HTTPS_ENABLED:-FALSE}
                VITE_API_PORT: ${API_PORT:-9000}
        restart: unless-stopped
        ports:
            - "${FRONTEND_PORT-3000}:3000"
        networks:
            - dnsnet
    watcher:
        container_name: dns-manager-docker-watcher
        build:
            context: ./watcher
            dockerfile: ./docker/Dockerfile
        restart: unless-stopped
        environment:
            - REMOTE=FALSE
            - API_HOST=dns-manager-backend:8000
            - HTTPS_ENABLED=${HTTPS_ENABLED:-FALSE}
            - WATCHER_NAME=${WATCHER_NAME}
            - TRAEFIK_HOST_IP=${TRAEFIK_HOST_IP}
            - WATCHER_AUTH_SECRET_KEY=${WATCHER_AUTH_SECRET_KEY}
            - LOG_LEVEL=${LOG_LEVEL:-INFO}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - dnsnet
networks:
    dnsnet:
        external: true
        name: dnsnet
