name: dns-manager-watcher

services:
    watcher:
        container_name: dns-manager-docker-watcher
        build:
            context: ./watcher
            dockerfile: ./docker/Dockerfile
        restart: unless-stopped
        environment:
            - REMOTE=TRUE
            - API_URL=${API_URL}
            - WATCHER_NAME=${WATCHER_NAME}
            - WATCHER_AUTH_SECRET_KEY=${WATCHER_AUTH_SECRET_KEY}
            - TRAEFIK_HOST_IP=${TRAEFIK_HOST_IP}
            - LOG_LEVEL=${LOG_LEVEL:-INFO}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - dnsnet
