name: dns-manager-dev

services:
    backend:
        container_name: dns-manager-backend-dev
        build:
            context: ./backend
            dockerfile: ./docker/Dockerfile.dev
        volumes:
            - ./backend/app:/backend/app
            - ./backend/migrations:/backend/migrations
        env_file:
            - .env
        ports:
            - "9000:8000"
        networks:
            - dnsnet
    frontend:
        container_name: dns-manager-frontend-dev
        build:
            context: ./webapp
            dockerfile: ./docker/Dockerfile.dev
        volumes:
            - ./webapp:/webapp
            - /webapp/node_modules
        ports:
            - "3000:5173"
        networks:
            - dnsnet
networks:
    dnsnet:
        external: true
        name: dnsnet
