FROM python:3.14-slim

WORKDIR /watcher

COPY --from=ghcr.io/astral-sh/uv:0.8.14 /uv /uvx /bin/

COPY pyproject.toml uv.lock ./

RUN uv sync --locked

COPY src ./src

CMD ["uv", "run", "--dev", "watchfiles", "python -m src.main", "src"]
