FROM python:3.14-slim

WORKDIR /backend

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock ./

RUN uv sync

COPY app ./app

CMD ["uv", "run", "python", "app.main:app", "--host", "0.0.0.0", "--port", "9000", "--reload"]