"""Initiate base schema

Revision ID: 227cf23ab612
Revises: 
Create Date: 2026-08-12 16:38:37.268264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '227cf23ab612'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_log',
    sa.Column('entry_uuid', sa.UUID(), nullable=False),
    sa.Column('action_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'WATCHER', name='actortype'), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'CHANGED', 'DELETED', 'RESTORED', 'PERMANENTLY_DELETED', name='changeaction'), nullable=False),
    sa.Column('affected_object', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('object_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('object_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('entry_uuid')
    )
    op.create_index(op.f('ix_action_log_action'), 'action_log', ['action'], unique=False)
    op.create_index(op.f('ix_action_log_actor'), 'action_log', ['actor'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('dns_records',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('zone', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('checks_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('origin', sa.Enum('MANUAL', 'AUTOMATIC', 'EXTERNAL', name='record_origin'), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.username'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('zone', 'name', 'type', 'content', name='unique_records_identifiers')
    )
    op.create_index(op.f('ix_dns_records_content'), 'dns_records', ['content'], unique=False)
    op.create_index(op.f('ix_dns_records_name'), 'dns_records', ['name'], unique=False)
    op.create_index(op.f('ix_dns_records_type'), 'dns_records', ['type'], unique=False)
    op.create_index(op.f('ix_dns_records_zone'), 'dns_records', ['zone'], unique=False)
    op.create_table('dns_zones',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.username'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('dns_record_trash',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('deletion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'WATCHER', name='dns_record_trash_actor_type'), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['dns_records.uuid'], name='fk_dns_record_trash_uuid_dns_records', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('dns_zone_trash',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('deletion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'WATCHER', name='dns_zone_trash_actor_type'), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['dns_zones.uuid'], name='fk_dns_zone_trash_uuid_dns_records', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dns_zone_trash')
    op.drop_table('dns_record_trash')
    op.drop_table('dns_zones')
    op.drop_index(op.f('ix_dns_records_zone'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_type'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_name'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_content'), table_name='dns_records')
    op.drop_table('dns_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_action_log_actor'), table_name='action_log')
    op.drop_index(op.f('ix_action_log_action'), table_name='action_log')
    op.drop_table('action_log')
    # ### end Alembic commands ###
