"""Add foreign key constraint between dns_records_metadata.zone_id and dns_zones_metadata.id

Revision ID: 2ad29c853a09
Revises: 5afbbd7143ab
Create Date: 2026-08-17 09:54:22.230161

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ad29c853a09"
down_revision: Union[str, Sequence[str], None] = "5afbbd7143ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_dns_records_metadata_zone_id", "dns_records_metadata", "dns_zones_metadata", ["zone_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_dns_records_metadata_zone_id", "dns_records_metadata", type_="foreignkey")
    # ### end Alembic commands ###
