"""Add affected_object_name column to action_log table

Revision ID: 6f41d0acdd8f
Revises: a555bb86f29f
Create Date: 2026-08-27 14:53:44.972858

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f41d0acdd8f"
down_revision: Union[str, Sequence[str], None] = "a555bb86f29f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("action_log", sa.Column("affected_object_name", sa.String(), nullable=False, server_default=""))
    op.create_index(op.f("ix_action_log_affected_object_name"), "action_log", ["affected_object_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_action_log_affected_object_name"), table_name="action_log")
    op.drop_column("action_log", "affected_object_name")
    # ### end Alembic commands ###
