"""Init base schema

Revision ID: a555bb86f29f
Revises:
Create Date: 2026-08-20 15:13:57.197104

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a555bb86f29f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_log",
        sa.Column("entry_uuid", sa.UUID(), nullable=False),
        sa.Column("action_timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor_type", sa.Enum("USER", "WATCHER", "AUTOMATIC", name="actortype"), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("CREATED", "CHANGED", "DELETED", "RESTORED", "PERMANENTLY_DELETED", name="changeaction"),
            nullable=False,
        ),
        sa.Column("affected_object_type", sa.Enum("ZONE", "RECORD", name="action_log_object_type"), nullable=False),
        sa.Column("object_before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("object_after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("entry_uuid"),
    )
    op.create_index(op.f("ix_action_log_action"), "action_log", ["action"], unique=False)
    op.create_index(op.f("ix_action_log_actor"), "action_log", ["actor"], unique=False)
    op.create_index(op.f("ix_action_log_affected_object_type"), "action_log", ["affected_object_type"], unique=False)
    op.create_table(
        "dns_trash",
        sa.Column("entry_uuid", sa.UUID(), nullable=False),
        sa.Column("deletion_timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("object_type", sa.Enum("ZONE", "RECORD", name="dns_trash_object_type"), nullable=False),
        sa.Column("object_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("entry_uuid"),
    )
    op.create_index(op.f("ix_dns_trash_actor"), "dns_trash", ["actor"], unique=False)
    op.create_index(op.f("ix_dns_trash_object_type"), "dns_trash", ["object_type"], unique=False)
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password", sa.String(length=60), nullable=False),
        sa.Column("full_name", sa.String(length=128), server_default="", nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("disabled", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_table(
        "dns_zones_metadata",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column("author", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["author"],
            ["users.username"],
            name="dns_zones_metadata_author_fkey",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "dns_records_metadata",
        sa.Column("zone_name", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column("checks_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("author", sa.String(length=64), nullable=True),
        sa.Column("origin", sa.Enum("MANUAL", "AUTOMATIC", name="internal_record_origin"), nullable=False),
        sa.ForeignKeyConstraint(
            ["author"],
            ["users.username"],
            name="dns_records_metadata_author_fkey",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["zone_name"], ["dns_zones_metadata.name"], name="fk_dns_records_metadata_zone_name", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("zone_name", "name", "type"),
    )
    op.create_index("ix_dns_records_metadata_zone_name", "dns_records_metadata", ["zone_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        "ix_dns_records_metadata_zone_name",
        table_name="dns_records_metadata",
    )
    op.drop_table("dns_records_metadata")

    op.drop_table("dns_zones_metadata")

    op.drop_index(
        op.f("ix_users_username"),
        table_name="users",
    )
    op.drop_table("users")

    op.drop_index(
        op.f("ix_dns_trash_object_type"),
        table_name="dns_trash",
    )
    op.drop_index(
        op.f("ix_dns_trash_actor"),
        table_name="dns_trash",
    )
    op.drop_table("dns_trash")

    op.drop_index(
        op.f("ix_action_log_affected_object_type"),
        table_name="action_log",
    )
    op.drop_index(
        op.f("ix_action_log_actor"),
        table_name="action_log",
    )
    op.drop_index(
        op.f("ix_action_log_action"),
        table_name="action_log",
    )
    op.drop_table("action_log")

    # PostgreSQL enum types.
    op.execute("DROP TYPE internal_record_origin")
    op.execute("DROP TYPE dns_trash_object_type")
    op.execute("DROP TYPE action_log_object_type")
    op.execute("DROP TYPE changeaction")
    op.execute("DROP TYPE actortype")
