"""Drop users <-> records metadata foreign key

Revision ID: ede00196f5a7
Revises: 6f41d0acdd8f
Create Date: 2026-09-14 13:06:07.745559

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ede00196f5a7"
down_revision: Union[str, Sequence[str], None] = "6f41d0acdd8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("dns_records_metadata_author_fkey"), "dns_records_metadata", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("dns_records_metadata_author_fkey"), "dns_records_metadata", "users", ["author"], ["username"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###
